openapi: 3.0.1
info:
  title: TODO Plugin
  description: 
    A plugin that helps you to play Go aka Baduk on a 9x9 board against the user. 
    You can start a new game, ask for the best move, make a move, get the move sequence, 
    get a position diagram, get the current score, or undo the last move. 
    The plugin uses the KataGo engine to make the moves. 
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /katachat/start_game:
    get:
      operationId: start_game
      summary: Start a new game. Resets the game record and returns a game id.
      parameters:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/start_game_resp'
  /katachat/get_best_move/{game_id}:
    get:
      operationId: get_best_move
      summary: Get the best next move in the current position for the game identified by game_id.
      parameters:
      - in: path
        name: game_id
        schema:
            type: string
        required: true
        description: The id of the game to get the best move for.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_best_move_resp'
        '5XX':
          description: Katachat error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/katachat_error'

components:
  schemas:
    start_game_resp:
      type: object
      properties:
        game_id:
          type: string
          description: The unique game identifier.
    get_best_move_resp:
      type: object
      properties:
        best_move:
          type: string
          description: The best move in the current position.
    katachat_error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.


    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of todos.
    addTodoRequest:
      type: object
      required:
      - todo
      properties:
        todo:
          type: string
          description: The todo to add to the list.
          required: true
    deleteTodoRequest:
      type: object
      required:
      - todo_idx
      properties:
        todo_idx:
          type: integer
          description: The index of the todo to delete.
          required: true